# Generated by Django 4.2.2 on 2023-08-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
